curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d 
'{
"users":[
   {
     "ID" : "kavFS93ANzRYgDZDHsaTB5N71Ob2",
    "username" : "user_1",
    "email" : "user_3@gmail.com",
    "password" : "******",
    "profile_image" : "https://firebase-cloud-store/toto.png"
  },
  {
    "ID" :  "LavFS93ANzRYgDZDHsaTB5N71Ob2",
    "username" : "user_2",
    "email" : "user_3@gmail.com",
    "password" : "******",
    "profile_image" : "https://firebase-cloud-store/toto.png"
  }

]
}' 
'http://localhost:8080/project/LvXGDbL9w1BsBCGczoi'