curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "deadline": "2000-01-23T04:56:07.000+00:00",
  "description": "description",
  "status": "pending",
  "users": [
    "4YrZBzvD4RTb6XoOOyvrVvopvv22",
  ]
}' 'http://localhost:8080/project/LvXC1i9mSDUGpHHBwFd'